import { AnimationDefinition, KrishnaState, PriorityLevel } from "./types";

export const ANIMATION_MAP: Record<KrishnaState, AnimationDefinition> = {
  idle: {
    state: "idle",
    frames: [
      "/emote/frames/idle_1.png",
      "/emote/frames/idle_2.png",
      "/emote/frames/idle_3.png",
      "/emote/frames/idle_4.png",
      "/emote/frames/idle_5.png",
      "/emote/frames/idle_6.png",
      "/emote/frames/idle_7.png",
      "/emote/frames/idle_8.png",
    ],
    frameInterval: 180,
    aspectRatio: "2:3",
    description: "Idle breathing / observation stance",
  },
  walk_left: {
    state: "walk_left",
    frames: [
      "/emote/frames/walk_left_1.png",
      "/emote/frames/walk_left_2.png",
      "/emote/frames/walk_left_3.png",
      "/emote/frames/walk_left_4.png",
      "/emote/frames/walk_left_5.png",
      "/emote/frames/walk_left_6.png",
    ],
    frameInterval: 110,
    aspectRatio: "2:3",
    description: "Walking left across the desktop",
  },
  walk_right: {
    state: "walk_right",
    frames: [
      "/emote/frames/walk_right_1.png",
      "/emote/frames/walk_right_2.png",
      "/emote/frames/walk_right_3.png",
      "/emote/frames/walk_right_4.png",
      "/emote/frames/walk_right_5.png",
      "/emote/frames/walk_right_6.png",
    ],
    frameInterval: 110,
    aspectRatio: "2:3",
    description: "Walking right across the desktop",
  },
  typing: {
    state: "typing",
    frames: [
      "/emote/frames/emote_typing_1.png",
      "/emote/frames/emote_typing_2.png",
    ],
    frameInterval: 280,
    aspectRatio: "1:1",
    gifUrl: "/emote/gifs/emote_typing.gif",
    description: "Typing code / building systems",
  },
  thinking: {
    state: "thinking",
    frames: [
      "/emote/frames/emote_thinking_1.png",
      "/emote/frames/emote_thinking_2.png",
    ],
    frameInterval: 320,
    aspectRatio: "1:1",
    gifUrl: "/emote/gifs/emote_thinking.gif",
    description: "Pondering architecture or algorithmic solution",
  },
  terminal: {
    state: "terminal",
    frames: [
      "/emote/frames/emote_terminal_1.png",
      "/emote/frames/emote_terminal_2.png",
    ],
    frameInterval: 300,
    aspectRatio: "1:1",
    gifUrl: "/emote/gifs/emote_terminal.gif",
    description: "Operating terminal shell / monitoring tty1",
  },
  success: {
    state: "success",
    frames: [
      "/emote/frames/emote_success_1.png",
      "/emote/frames/emote_success_2.png",
    ],
    frameInterval: 250,
    aspectRatio: "1:1",
    gifUrl: "/emote/gifs/emote_success.gif",
    description: "Command success / celebration",
  },
  error: {
    state: "error",
    frames: [
      "/emote/frames/emote_error_1.png",
      "/emote/frames/emote_error_2.png",
    ],
    frameInterval: 250,
    aspectRatio: "1:1",
    gifUrl: "/emote/gifs/emote_error.gif",
    description: "System error alert / exception caught",
  },
  happy: {
    state: "happy",
    frames: [
      "/emote/frames/emote_happy_1.png",
      "/emote/frames/emote_happy_2.png",
    ],
    frameInterval: 250,
    aspectRatio: "1:1",
    gifUrl: "/emote/gifs/emote_happy.gif",
    description: "Happy / friendly greeting",
  },
  confused: {
    state: "confused",
    frames: [
      "/emote/frames/emote_confused_1.png",
      "/emote/frames/emote_confused_2.png",
    ],
    frameInterval: 320,
    aspectRatio: "1:1",
    gifUrl: "/emote/gifs/emote_confused.gif",
    description: "Confused by invalid input or syntax error",
  },
  chai: {
    state: "chai",
    frames: [
      "/emote/frames/emote_chai_1.png",
      "/emote/frames/emote_chai_2.png",
    ],
    frameInterval: 350,
    aspectRatio: "1:1",
    gifUrl: "/emote/gifs/emote_chai.gif",
    description: "Drinking warm chai tea / taking a break",
  },
  reading: {
    state: "reading",
    frames: [
      "/emote/frames/emote_reading_1.png",
      "/emote/frames/emote_reading_2.png",
    ],
    frameInterval: 350,
    aspectRatio: "1:1",
    gifUrl: "/emote/gifs/emote_reading.gif",
    description: "Reading documentation / inspecting resume",
  },
  sleeping: {
    state: "sleeping",
    frames: [
      "/emote/frames/emote_sleep_1.png",
      "/emote/frames/emote_sleep_2.png",
    ],
    frameInterval: 500,
    aspectRatio: "1:1",
    gifUrl: "/emote/gifs/emote_sleep.gif",
    description: "Idle power-save mode (sleeping zzz)",
  },
};

export const STATE_PRIORITIES: Record<KrishnaState, PriorityLevel> = {
  error: 4,
  confused: 4,
  success: 3,
  happy: 3,
  chai: 3,
  terminal: 2,
  typing: 2,
  reading: 2,
  thinking: 2,
  walk_left: 1,
  walk_right: 1,
  idle: 0,
  sleeping: 0,
};
